steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-R', 'gs://$PROJECT_ID/proxy_cache', '/builder/home/.cache/.cache']

- name: 'gcr.io/istio-io/istio-builder:0.3.2'
  args: ['make', 'artifacts', "ISTIO_TAGS=git_latest"]
#- name: 'gcr.io/istio-io/istio-builder:0.1'
#  # TODO: create a 'repo' build step
#  args: ['./script/build_repo.sh', 'sync']

# Build the docker images - images will upload them
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/proxy_debug', '-f', 'bazel-bin/src/envoy/mixer/Dockerfile.debug', 'bazel-bin/src/envoy/mixer' ]

# Build other artifacts ( deb files )
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'bazel-bin/tools/deb/istio-proxy.deb', 'gs://istio/istio-proxy-master.deb']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'go/src/istio.io/pilot/bazel-bin/tools/deb/istio-agent.deb', 'gs://istio/istio-agent-master.deb']

images:
-  'gcr.io/$PROJECT_ID/proxy_debug'

timeout: 1800s
